config/routes.rb
CloudDrive::Application.routes.draw do

  resources :cloud_files

  devise_for :admins, :only => :session, :controllers => { :sessions => "admins/sessions" }

  devise_for :clients

  namespace :admins do
    
    resources :clients

  end

  root :to => "pages#index"

    
  match '/auth' => 'pages#auth'
  match '/welcome' => 'pages#welcome'
  match '/home' => 'pages#home'
  match '/setting' => 'pages#setting'

end

app/models/cloud_file.rb
class CloudFile
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :description, type: String
  field :filename, type: String

  field :data_secure_token, type: String

  mount_uploader :data, FileUploader

  belongs_to :client
  
  validates :name, uniqueness: true, presence: true

end

app/controllers/cloud_files_controller.rb
class CloudFilesController < ApplicationController
  # GET /cloud_files
  # GET /cloud_files.json
  def index
    @cloud_files = CloudFile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cloud_files }
    end
  end

  # GET /cloud_files/1
  # GET /cloud_files/1.json
  def show
    @cloud_file = CloudFile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cloud_file }
    end
  end

  # GET /cloud_files/new
  # GET /cloud_files/new.json
  def new
    @cloud_file = CloudFile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cloud_file }
    end
  end

  # GET /cloud_files/1/edit
  def edit
    @cloud_file = CloudFile.find(params[:id])
  end

  # POST /cloud_files
  # POST /cloud_files.json
  def create
    @cloud_file = CloudFile.new(params[:cloud_file])

    @cloud_file.client_id = current_client.id

    respond_to do |format|
      if @cloud_file.save
        format.html { redirect_to "/home", notice: 'Cloud file was successfully created.' }
        format.json { render json: @cloud_file, status: :created, location: @cloud_file }
      else
        format.html { render action: "new" }
        format.json { render json: @cloud_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cloud_files/1
  # PUT /cloud_files/1.json
  def update
    @cloud_file = CloudFile.find(params[:id])

    respond_to do |format|
      if @cloud_file.update_attributes(params[:cloud_file])
        format.html { redirect_to @cloud_file, notice: 'Cloud file was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cloud_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cloud_files/1
  # DELETE /cloud_files/1.json
  def destroy
    @cloud_file = CloudFile.find(params[:id])
    @cloud_file.destroy

    respond_to do |format|
      format.html { redirect_to cloud_files_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cloud_files_helper.rb
module CloudFilesHelper
end

app/views/cloud_files/_form.html.erb
<%= form_for(@cloud_file) do |f| %>
  <% if @cloud_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cloud_file.errors.count, "error") %> prohibited this cloud_file from being saved:</h2>

      <ul>
      <% @cloud_file.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.file_field :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cloud_files/edit.html.erb
<h1>Editing cloud_file</h1>

<%= render 'form' %>

<%= link_to 'Show', @cloud_file %> |
<%= link_to 'Back', cloud_files_path %>

app/views/cloud_files/index.html.erb
<h1>Listing cloud_files</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Data</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cloud_files.each do |cloud_file| %>
  <tr>
    <td><%= cloud_file.name %></td>
    <td><%= cloud_file.description %></td>
    <td><a href="<%= cloud_file.data %>">Download</a></td>
    <td><%= link_to 'Show', cloud_file %></td>
    <td><%= link_to 'Edit', edit_cloud_file_path(cloud_file) %></td>
    <td><%= link_to 'Destroy', cloud_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cloud file', new_cloud_file_path %>

app/views/cloud_files/new.html.erb
<h1>New cloud_file</h1>

<%= render 'form' %>

<%= link_to 'Back', cloud_files_path %>

app/views/cloud_files/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Name:</b>
  <%= @cloud_file.name %>
</p>

<p>
  <b>Description:</b>
  <%= @cloud_file.description %>
</p>

<p>
  <b>Data:</b>
  <%= @cloud_file.data %>
</p>


<%= link_to 'Edit', edit_cloud_file_path(@cloud_file) %> |
<%= link_to 'Back', cloud_files_path %>